services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: app
    ports:
      - "8080:80"
    environment:
      APP_DEVELOP_MODE: true
      APP_NAMESPACE: "local"
    volumes:
      - ..:/var/www/app
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    environment:
      LANG: "C.UTF-8"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  redis:
    image: redis:alpine
